const express=require('express')
const app=express()
const rout=require('./router/StudentRout')
const bodyparser=require('body-parser')
const cors=require('cors')
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(cors())
console.log("index page")
app.use('/',rout)
app.listen(3005,console.log("server is runing"))